// grid
export const ADD_COLUMN = 'ADD_COLUMN';
export const ADD_ROW = 'ADD_ROW';
export const DELETE_COLUMN = 'DELETE_COLUMN';
export const DELETE_ROW = 'DELETE_ROW';
export const RESET_TABLE = 'RESET_TABLE';
export const HIGHLIGHT_DELETION = 'HIGHLIGHT_DELETION';
export const REMOVE_HIGHLIGHT = 'REMOVE_HIGHLIGHT';
export const CHANGE_CELL_STYLE = 'CHANGE_CELL_STYLE';

// menu
export const OPEN_CONTEXT_MENU = 'OPEN_CONTEXT_MENU';
export const OPEN_COLOR_MENU = 'OPEN_COLOR_MENU';
export const CLOSE_ALL_MENUES = 'CLOSE_ALL_MENUES';
export const CLOSE_COLOR_MENU = 'CLOSE_COLOR_MENU';
export const BACK_FROM_COLOR_MENU = 'BACK_FROM_COLOR_MENU';
export const ANIMATE_COLUMN_DELETION = 'ANIMATE_COLUMN_DELETION';
export const ANIMATE_ROW_DELETION = 'ANIMATE_ROW_DELETION';